diff --git a/extensions/browser/extension_function_histogram_value.h b/extensions/browser/extension_function_histogram_value.h
index daced4aed4d50..804539041fa01 100644
--- a/extensions/browser/extension_function_histogram_value.h
+++ b/extensions/browser/extension_function_histogram_value.h
@@ -1997,6 +1997,27 @@ enum HistogramValue {
   EXPERIMENTALACTOR_STARTTASK = 1934,
   EXPERIMENTALACTOR_EXECUTEACTION = 1935,
   EXPERIMENTALACTOR_STOPTASK = 1936,
+  JACKIE_BROWSER_GETACCESSIBILITYTREE = 1937,
+  JACKIE_BROWSER_GETINTERACTIVESNAPSHOT = 1938,
+  JACKIE_BROWSER_CLICK = 1939,
+  JACKIE_BROWSER_INPUTTEXT = 1940,
+  JACKIE_BROWSER_CLEAR = 1941,
+  JACKIE_BROWSER_GETPAGELOADSTATUS = 1942,
+  JACKIE_BROWSER_SCROLLUP = 1943,
+  JACKIE_BROWSER_SCROLLDOWN = 1944,
+  JACKIE_BROWSER_SCROLLTONODE = 1945,
+  JACKIE_BROWSER_SENDKEYS = 1946,
+  JACKIE_BROWSER_GETPAGESTRUCTURE = 1947,
+  JACKIE_BROWSER_CAPTURESCREENSHOT = 1948,
+  JACKIE_BROWSER_GETSNAPSHOT = 1949,
+  JACKIE_BROWSER_GETPREF = 1950,
+  JACKIE_BROWSER_SETPREF = 1951,
+  JACKIE_BROWSER_GETALLPREFS = 1952,
+  JACKIE_BROWSER_LOGMETRIC = 1953,
+  JACKIE_BROWSER_GETVERSIONNUMBER = 1954,
+  JACKIE_BROWSER_EXECUTEJAVASCRIPT = 1955,
+  JACKIE_BROWSER_CLICKCOORDINATES = 1956,
+  JACKIE_BROWSER_TYPEATCOORDINATES = 1957,
   // Last entry: Add new entries above, then run:
   // tools/metrics/histograms/update_extension_histograms.py
   ENUM_BOUNDARY
